// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3OR4EHqbgKsvayQNOD5-fvHjWz0NiG9g',
    appId: '1:757341902860:web:c85e6120707433cdf47629',
    messagingSenderId: '757341902860',
    projectId: 'sbuffed-racing-app',
    authDomain: 'sbuffed-racing-app.firebaseapp.com',
    storageBucket: 'sbuffed-racing-app.appspot.com',
    measurementId: 'G-GP0KH4KL6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_U6mtXomtEd8Dxcm-CTe9wHG62yhu_p8',
    appId: '1:757341902860:android:1628a8fb886deaa4f47629',
    messagingSenderId: '757341902860',
    projectId: 'sbuffed-racing-app',
    storageBucket: 'sbuffed-racing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdNn_9S6z2Ucwdpu2IGrxWkf0ypWcUrY',
    appId: '1:757341902860:ios:aa948293f60bff67f47629',
    messagingSenderId: '757341902860',
    projectId: 'sbuffed-racing-app',
    storageBucket: 'sbuffed-racing-app.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdNn_9S6z2Ucwdpu2IGrxWkf0ypWcUrY',
    appId: '1:757341902860:ios:aa948293f60bff67f47629',
    messagingSenderId: '757341902860',
    projectId: 'sbuffed-racing-app',
    storageBucket: 'sbuffed-racing-app.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3OR4EHqbgKsvayQNOD5-fvHjWz0NiG9g',
    appId: '1:757341902860:web:d700e6f9f55937dff47629',
    messagingSenderId: '757341902860',
    projectId: 'sbuffed-racing-app',
    authDomain: 'sbuffed-racing-app.firebaseapp.com',
    storageBucket: 'sbuffed-racing-app.appspot.com',
    measurementId: 'G-0KN8EQBTPS',
  );

}